global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'srvs-one'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['consumer-service:4000']
  - job_name: 'srvs-two'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['producer-service:4000']